import { addEntity, createProject, getChildren, getEntity, removeEntity, updateEntity } from '../core/projectGraph.js';
import { buildFileTree, createProjectFiles, findProjectFile, upsertProjectFile } from '../core/projectFiles.js';
import { canRedo, canUndo, commitHistory, createHistory, redo, undo } from '../core/history.js';
import { getViewport } from './responsive.js';

let graph = createProject({ name: 'Untitled Project' });
graph = addEntity(graph,{type:'page',name:'Home',parentId:graph.projectId,data:{route:'/'}});
let pages = getChildren(graph,graph.projectId).filter(e=>e.type==='page');
let selectedPageId=pages[0].id, selectedId=null, projectFiles=createProjectFiles(), activeFilePath='frontend/pages/Home.html', device='desktop';
let history=createHistory(graph);
const canvas=document.querySelector('#canvas'),tree=document.querySelector('#layerTree'),inspector=document.querySelector('#inspector'),selectionInfo=document.querySelector('#selectionInfo');
const labels={section:'Section',heading:'Heading',text:'Text',button:'Button',image:'Image'}, defaults={width:'auto',minHeight:'auto',background:'',color:'',padding:'18px',margin:'18px',borderRadius:'0px',display:'block',flexDirection:'row',gap:'12px',gridColumns:'repeat(2, 1fr)'};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const activePage=()=>getEntity(graph,selectedPageId), styleOf=n=>({...defaults,...(n.data?.styles??{})});
function contentFor(t){return t==='heading'?'<h1>New Heading</h1>':t==='text'?'<p>Start writing here...</p>':t==='button'?'<button>Click me</button>':t==='image'?'<div class="image-placeholder">Image placeholder</div>':'<div><h2>New Section</h2><p>Section content</p></div>'}
function commit(next){graph=next;history=commitHistory(history,graph);render()}
function targetParent(){const n=selectedId?getEntity(graph,selectedId):null;return n?.data?.type==='section'?n.id:selectedPageId}
function add(t){const p=targetParent(),next=addEntity(graph,{type:'element',name:labels[t],parentId:p,data:{type:t,content:contentFor(t),styles:{...defaults}}});commit(next);selectedId=getChildren(next,p).at(-1)?.id;render()}
function addPage(){const n=pages.length+1,next=addEntity(graph,{type:'page',name:`Page ${n}`,parentId:graph.projectId,data:{route:`/page-${n}`}});commit(next);pages=getChildren(next,next.projectId).filter(e=>e.type==='page');selectedPageId=pages.at(-1).id;selectedId=null;render()}
function renderNode(n){const s=styleOf(n),el=document.createElement('div');el.className=`forge-node ${n.id===selectedId?'selected':''}`;el.dataset.id=n.id;Object.assign(el.style,{width:s.width,minHeight:s.minHeight,background:s.background,color:s.color,padding:s.padding,margin:s.margin,borderRadius:s.borderRadius,display:s.display,flexDirection:s.flexDirection,gap:s.gap,gridTemplateColumns:s.gridColumns});el.innerHTML=n.data?.content??'';if(n.id===selectedId)['nw','ne','sw','se'].forEach(pos=>{const h=document.createElement('span');h.className=`resize-handle ${pos}`;h.dataset.handle=pos;el.appendChild(h)});el.onclick=e=>{if(e.target.classList.contains('resize-handle'))return;e.stopPropagation();selectedId=n.id;render()};getChildren(graph,n.id).forEach(c=>el.appendChild(renderNode(c)));return el}
function renderTree(n,d=0){const w=document.createElement('div'),i=document.createElement('div');i.className=`tree-item ${n.id===selectedId?'selected':''}`;i.style.paddingLeft=`${8+d*14}px`;i.textContent=`${getChildren(graph,n.id).length?'▾':'•'} ${n.name}`;i.onclick=()=>{selectedId=n.id;render()};w.appendChild(i);getChildren(graph,n.id).forEach(c=>w.appendChild(renderTree(c,d+1)));return w}
function renderPages(){const root=document.querySelector('#pages');if(!root)return;pages=getChildren(graph,graph.projectId).filter(e=>e.type==='page');root.innerHTML=pages.map(p=>`<button class="page-item ${p.id===selectedPageId?'selected':''}" data-page="${p.id}">▣ ${esc(p.name)}</button>`).join('');root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{selectedPageId=b.dataset.page;selectedId=null;render()})}
function renderFiles(){const root=document.querySelector('#fileTree');if(!root)return;root.innerHTML='';const walk=(n,d=0)=>{const e=document.createElement('div');e.className=`file-item ${n.path===activeFilePath?'selected':''}`;e.style.paddingLeft=`${8+d*13}px`;e.textContent=`${n.type==='folder'?'▾':'•'} ${n.name}`;if(n.type==='file')e.onclick=()=>openFile(n.path);root.appendChild(e);n.children.forEach(c=>walk(c,d+1))};walk(buildFileTree(projectFiles))}
function pageCode(){return `<!-- WebForge generated page: ${esc(activePage()?.name)} -->\n${getChildren(graph,selectedPageId).map(n=>n.data?.content??'').join('\n')}`}
function openFile(path){activeFilePath=path;const f=findProjectFile(projectFiles,path);const ed=document.querySelector('#codeEditor');if(ed)ed.value=f?.content||pageCode();const af=document.querySelector('#activeFile');if(af)af.textContent=path;renderFiles()}
function inspectorFor(){if(!selectedId){selectionInfo.textContent='Nothing selected';inspector.innerHTML='<p>Select an element to edit its properties.</p>';return}const n=getEntity(graph,selectedId);selectionInfo.textContent=n?.name??'Nothing selected';if(!n)return;const s=styleOf(n);inspector.innerHTML=`<div class="field"><label>Name</label><input id="name" value="${esc(n.name)}"></div><div class="field"><label>Layout</label><select id="display"><option value="block" ${s.display==='block'?'selected':''}>Block</option><option value="flex" ${s.display==='flex'?'selected':''}>Flex</option><option value="grid" ${s.display==='grid'?'selected':''}>Grid</option></select></div><div class="field"><label>Width</label><input id="width" value="${esc(s.width)}"></div><div class="field"><label>Min height</label><input id="minHeight" value="${esc(s.minHeight)}"></div><div class="field"><label>Padding</label><input id="padding" value="${esc(s.padding)}"></div><div class="field"><label>Margin</label><input id="margin" value="${esc(s.margin)}"></div><div class="field"><label>Gap</label><input id="gap" value="${esc(s.gap)}"></div><div class="field"><label>Background</label><input id="background" value="${esc(s.background)}"></div><div class="field"><label>Text color</label><input id="color" value="${esc(s.color)}"></div><div class="field"><label>Radius</label><input id="radius" value="${esc(s.borderRadius)}"></div><div class="field"><label>Flex direction</label><select id="flexDirection"><option value="row" ${s.flexDirection==='row'?'selected':''}>row</option><option value="column" ${s.flexDirection==='column'?'selected':''}>column</option></select></div><div class="field"><label>Grid columns</label><input id="gridColumns" value="${esc(s.gridColumns)}"></div><div class="field"><label>Content</label><textarea id="content">${esc(n.data?.content??'')}</textarea></div><button id="delete" class="danger">Delete element</button>`;const patch=()=>{const ns={...s,width:inspector.querySelector('#width').value,minHeight:inspector.querySelector('#minHeight').value,padding:inspector.querySelector('#padding').value,margin:inspector.querySelector('#margin').value,gap:inspector.querySelector('#gap').value,background:inspector.querySelector('#background').value,color:inspector.querySelector('#color').value,borderRadius:inspector.querySelector('#radius').value,display:inspector.querySelector('#display').value,flexDirection:inspector.querySelector('#flexDirection').value,gridColumns:inspector.querySelector('#gridColumns').value};const next=updateEntity(graph,selectedId,{name:inspector.querySelector('#name').value,data:{...n.data,content:inspector.querySelector('#content').value,styles:ns}});commit(next);selectedId=n.id;render()};inspector.querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('change',patch));inspector.querySelector('#delete').onclick=()=>{commit(removeEntity(graph,selectedId));selectedId=null;render()}}
function render(){pages=getChildren(graph,graph.projectId).filter(e=>e.type==='page');if(!getEntity(graph,selectedPageId))selectedPageId=pages[0]?.id;canvas.innerHTML='';const children=getChildren(graph,selectedPageId);if(!children.length)canvas.innerHTML='<div class="drop-hint">Drag an element here to start building</div>';else children.forEach(n=>canvas.appendChild(renderNode(n)));tree.innerHTML=children.length?'':'<div class="empty">No layers yet</div>';children.forEach(n=>tree.appendChild(renderTree(n)));renderPages();renderFiles();inspectorFor();const vp=getViewport(device);canvas.style.width=`min(${vp.width}px, calc(100% - 44px))`;document.querySelector('#viewportInfo').textContent=`${vp.width}px`;document.querySelectorAll('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===device));document.querySelector('#undoBtn').disabled=!canUndo(history);document.querySelector('#redoBtn').disabled=!canRedo(history)}
function resize(e){const n=getEntity(graph,selectedId),el=canvas.querySelector(`[data-id="${selectedId}"]`);if(!n||!el)return;const r=el.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,sw=r.width,sh=r.height,handle=e.target.dataset.handle;const move=ev=>{const dx=ev.clientX-sx,dy=ev.clientY-sy;const w=Math.max(40,sw+(handle.includes('e')?dx:-dx)),h=Math.max(30,sh+(handle.includes('s')?dy:-dy));const next=updateEntity(graph,selectedId,{data:{...n.data,styles:{...styleOf(n),width:`${Math.round(w)}px`,minHeight:`${Math.round(h)}px`}}});graph=next;render()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);history=commitHistory(history,graph);render()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
canvas.addEventListener('pointerdown',e=>{if(e.target.classList.contains('resize-handle')){e.stopPropagation();resize(e)}});document.querySelectorAll('.element').forEach(b=>{b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.type));b.onclick=()=>add(b.dataset.type)});canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const t=e.dataTransfer.getData('text/plain');if(t)add(t)};canvas.onclick=()=>{selectedId=null;render()};
document.querySelector('#addPage')?.addEventListener('click',addPage);document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;render()});document.querySelector('#undoBtn').onclick=()=>{history=undo(history);graph=structuredClone(history.present);selectedId=null;render()};document.querySelector('#redoBtn').onclick=()=>{history=redo(history);graph=structuredClone(history.present);selectedId=null;render()};
document.querySelector('#saveFile')?.addEventListener('click',()=>{const ed=document.querySelector('#codeEditor');projectFiles=upsertProjectFile(projectFiles,{path:activeFilePath,kind:'source',language:'html',content:ed?.value??''});renderFiles()});document.querySelector('#previewBtn').onclick=()=>{const win=window.open('','_blank');win.document.write(`<!doctype html><html><body>${getChildren(graph,selectedPageId).map(n=>n.data?.content??'').join('')}</body></html>`);win.document.close()};document.querySelector('#exportBtn').onclick=()=>{const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WebForge Export</title></head><body>${getChildren(graph,selectedPageId).map(n=>n.data?.content??'').join('')}</body></html>`;const blob=new Blob([html],{type:'text/html'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='webforge-page.html';a.click();URL.revokeObjectURL(a.href)};
openFile(activeFilePath);render();