import {ACTIONS,getAction,setAction} from '../core/navigationGraph.js';
const KEY='webforge-navigation-v1';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'')||{version:1,edges:{}}}catch{return{version:1,edges:{}}}};
const save=v=>{localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new CustomEvent('webforge:navigationchange'))};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function selected(){return document.querySelector('#canvas .forge-node.selected')?.dataset.id||null}
function graph(){return window.webforge?.getGraph?.()||null}
function findPages(){return Object.values(graph()?.entities||{}).filter(e=>e.type==='page')}
function mount(){const inspector=document.querySelector('#inspector');if(!inspector)return;const observer=new MutationObserver(()=>render());observer.observe(inspector,{childList:true,subtree:true});render()}
function render(){const inspector=document.querySelector('#inspector'),g=graph(),id=selected();if(!inspector||!g||!id)return;const node=g.entities?.[id];if(node?.data?.type!=='button')return;let panel=inspector.querySelector('.action-editor');if(!panel){panel=document.createElement('div');panel.className='action-editor';inspector.appendChild(panel)}const nav=load(),current=getAction(nav,id),pages=findPages(),action=current?.action||'none';panel.innerHTML=`<div class="field"><label>Button Action</label><select id="buttonAction">${ACTIONS.map(a=>`<option value="${a}" ${a===action?'selected':''}>${a.replaceAll('-',' ')}</option>`).join('')}</select></div><div id="actionTarget"></div>`;const select=panel.querySelector('#buttonAction'),target=panel.querySelector('#actionTarget');const renderTarget=()=>{const a=select.value;if(a==='open-page'){target.innerHTML=`<div class="field"><label>Target Page</label><select id="pageTarget">${pages.map(p=>`<option value="${p.id}" ${p.id===current?.target?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div>`}else if(a==='open-url'){target.innerHTML='<div class="field"><label>URL</label><input id="actionValue" placeholder="https://example.com"></div>'}else if(a==='scroll-to-section'){target.innerHTML='<div class="field"><label>Section ID</label><input id="actionValue" placeholder="#pricing"></div>'}else if(a==='open-modal'){target.innerHTML='<div class="field"><label>Modal ID</label><input id="actionValue" placeholder="contact-modal"></div>'}else if(a==='run-javascript'){target.innerHTML='<div class="field"><label>JavaScript</label><textarea id="actionValue" placeholder="console.log(\'clicked\')"></textarea></div>'}else target.innerHTML='';};renderTarget();select.onchange=()=>{if(select.value==='none'){save(setAction(load(),id,'none'));return}renderTarget();const value=panel.querySelector('#pageTarget,#actionValue')?.value||'';save(setAction(load(),id,select.value,value))};panel.addEventListener('change',e=>{if(e.target?.id==='pageTarget'||e.target?.id==='actionValue')save(setAction(load(),id,select.value,e.target.value))},{once:false});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
export function getNavigationGraph(){return load()}
