import { buildPageMap } from '../core/navigationGraph.js';
import { getBranchParent } from '../core/pageBranches.js';

const style=()=>{if(document.querySelector('#webforgePageMapV27'))return;const s=document.createElement('style');s.id='webforgePageMapV27';s.textContent=`.wf27-map{position:relative;flex:1;overflow:hidden;background:#080b11;cursor:grab}.wf27-map.dragging{cursor:grabbing}.wf27-world{position:absolute;left:0;top:0;width:4000px;height:3000px;transform-origin:0 0}.wf27-svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible;pointer-events:none}.wf27-node{position:absolute;width:190px;min-height:72px;padding:11px 13px;border:1px solid #394055;border-radius:12px;background:#141925;color:#edf1fa;text-align:left;box-shadow:0 12px 28px #0007;cursor:pointer;z-index:3}.wf27-node:hover{border-color:#8b79ff}.wf27-node strong{display:block;font-size:12px}.wf27-node span{display:block;margin-top:5px;font-size:9px;color:#8d97ab}.wf27-node.branch{border-color:#476f62}.wf27-node.root{border-color:#7c5cff}.wf27-edge{fill:none;stroke:#7063b6;stroke-width:2.2;opacity:.72}.wf27-edge.branch{stroke:#4d8a70;stroke-width:2.6}.wf27-label{font-size:10px;fill:#b8bfd0;paint-order:stroke;stroke:#080b11;stroke-width:4px}.wf27-tools{position:absolute;z-index:10;right:14px;top:14px;display:flex;gap:6px}.wf27-tools button{border:1px solid #303649;background:#151a25;color:#dfe5f2;border-radius:7px;padding:6px 9px;cursor:pointer}.wf27-tools button:hover{border-color:#7c5cff}.wf27-legend{position:absolute;left:14px;bottom:14px;z-index:10;padding:7px 9px;border:1px solid #293044;border-radius:8px;background:#101520;color:#8993a8;font-size:10px}`;document.head.appendChild(s)};
function pageList(graph){return Object.values(graph?.entities||{}).filter(e=>e.type==='page')}
function openPageMap(){style();const graph=window.webforge?.getGraph?.();const nav=window.webforge?.getNavigationGraph?.()||{edges:{}};const map=buildPageMap(graph,nav);const pages=pageList(graph);const root=document.createElement('div');root.className='webforge-overlay';root.innerHTML=`<div class="webforge-modal page-map-modal"><div class="webforge-modal-head"><div class="webforge-modal-title">Page Map</div><div class="webforge-modal-subtitle">Branches + navigation</div><div class="webforge-modal-spacer"></div><button class="webforge-modal-close">Close</button></div><div class="wf27-map"><div class="wf27-tools"><button data-z="-0.1">−</button><button data-z="reset">Reset</button><button data-z="0.1">＋</button></div><div class="wf27-world"><svg class="wf27-svg"></svg></div><div class="wf27-legend">Green = branch relationship · Purple = navigation</div></div></div>`;root.querySelector('.webforge-modal-close').onclick=()=>root.remove();root.onclick=e=>{if(e.target===root)root.remove()};document.body.appendChild(root);const viewport=root.querySelector('.wf27-map'),world=root.querySelector('.wf27-world'),svg=root.querySelector('.wf27-svg');const positions=JSON.parse(localStorage.getItem('webforge-page-map-positions-v27')||'{}');let scale=1,panX=20,panY=20,drag=null;
 const positionFor=(page,index)=>positions[page.id]||{x:80+(index%4)*300,y:80+Math.floor(index/4)*180};
 pages.forEach((page,index)=>{const pos=positionFor(page,index);const node=document.createElement('button');node.className=`wf27-node ${page.data?.branchParentId?'branch':'root'}`;node.dataset.id=page.id;node.style.left=`${pos.x}px`;node.style.top=`${pos.y}px`;node.innerHTML=`<strong>◉ ${page.name}</strong><span>${page.data?.route||'/'}</span>`;node.ondblclick=()=>{document.querySelector(`[data-page="${page.id}"]`)?.click();root.remove()};node.onpointerdown=e=>{e.stopPropagation();const start={x:e.clientX,y:e.clientY,px:parseFloat(node.style.left),py:parseFloat(node.style.top)};node.setPointerCapture?.(e.pointerId);const move=ev=>{node.style.left=`${start.px+(ev.clientX-start.x)/scale}px`;node.style.top=`${start.py+(ev.clientY-start.y)/scale}px`;draw()};const up=()=>{const all=JSON.parse(localStorage.getItem('webforge-page-map-positions-v27')||'{}');all[page.id]={x:parseFloat(node.style.left),y:parseFloat(node.style.top)};localStorage.setItem('webforge-page-map-positions-v27',JSON.stringify(all));node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up)};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up);};world.appendChild(node)});
 viewport.onpointerdown=e=>{if(e.target!==viewport)return;drag={x:e.clientX,y:e.clientY,px:panX,py:panY};viewport.classList.add('dragging');viewport.setPointerCapture?.(e.pointerId)};viewport.onpointermove=e=>{if(!drag)return;panX=drag.px+e.clientX-drag.x;panY=drag.py+e.clientY-drag.y;applyTransform()};viewport.onpointerup=()=>{drag=null;viewport.classList.remove('dragging')};viewport.onwheel=e=>{e.preventDefault();scale=Math.min(2.2,Math.max(.45,scale+(e.deltaY<0?.08:-.08)));applyTransform()};
 function path(a,b){const x1=a.x+190,y1=a.y+36,x2=b.x,y2=b.y+36,dx=Math.max(50,(x2-x1)/2);return `M ${x1} ${y1} C ${x1+dx} ${y1}, ${x2-dx} ${y2}, ${x2} ${y2}`}
 function draw(){svg.innerHTML='';svg.setAttribute('viewBox','0 0 4000 3000');const getPos=id=>{const el=world.querySelector(`[data-id="${id}"]`);return el?{x:parseFloat(el.style.left),y:parseFloat(el.style.top)}:null};const edge=(a,b,label,kind)=>{const p=path(a,b),q=document.createElementNS('http://www.w3.org/2000/svg','path');q.setAttribute('d',p);q.setAttribute('class',`wf27-edge ${kind}`);svg.appendChild(q);if(label){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('class','wf27-label');t.setAttribute('x',(a.x+b.x+190)/2);t.setAttribute('y',(a.y+b.y)/2+24);t.textContent=label;svg.appendChild(t)}};pages.forEach((page)=>{const parent=getBranchParent(graph,page.id);if(parent){const a=getPos(parent.id),b=getPos(page.id);if(a&&b)edge(a,b,'','branch')}});map.edges.forEach(e=>{if(!e.targetPageId)return;const a=getPos(e.sourcePageId),b=getPos(e.targetPageId);if(a&&b)edge(a,b,e.action,'nav')})}
 function applyTransform(){world.style.transform=`translate(${panX}px,${panY}px) scale(${scale})`;draw()}
 root.querySelectorAll('[data-z]').forEach(b=>b.onclick=()=>{const z=b.dataset.z;if(z==='reset'){scale=1;panX=20;panY=20}else scale=Math.min(2.2,Math.max(.45,scale+Number(z)));applyTransform()});applyTransform();return root}
export {openPageMap};
