const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const slugify = value => String(value || 'page').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') || 'page';
const cssName = value => value.replace(/[A-Z]/g, m => `-${m.toLowerCase()}`);
const styleRules = styles => Object.entries(styles || {}).filter(([,value]) => value !== '' && value != null && value !== 'auto').map(([key,value]) => `${cssName(key)}:${value};`).join('');
const tagFor = type => ({section:'section',heading:'h1',text:'p',button:'button',image:'figure'}[type] || 'div');

function semanticNode(graph, node){
  const type = node.data?.type || 'div';
  const tag = tagFor(type);
  const classes = [`wf-${node.id}`];
  if(node.data?.componentId) classes.push(`component-${slugify(node.data.componentId)}`);
  const attrs = ` class="${classes.join(' ')}" data-wf-id="${esc(node.id)}"`;
  const children = (node.children || []).map(id => graph.entities[id]).filter(Boolean).map(child => semanticNode(graph, child)).join('\n');
  let content = node.data?.content || '';
  if(type === 'heading') content = String(content).replace(/^<h1[^>]*>|<\/h1>$/gi, '');
  if(type === 'text') content = String(content).replace(/^<p[^>]*>|<\/p>$/gi, '');
  if(type === 'button') content = esc(String(content).replace(/<[^>]+>/g,'').trim() || 'Button');
  if(type === 'image') content = '<img src="../assets/placeholder.svg" alt="Image">';
  return `<${tag}${attrs}>${content}${children}</${tag}>`;
}

function collectGraphFiles(graph){
  const pages = Object.values(graph.entities || {}).filter(entity => entity.type === 'page');
  const files = {};
  const globalCss = `/* Generated by WebForge */\n:root{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111827;background:#fff;}\n*{box-sizing:border-box;}\nhtml,body{margin:0;padding:0;min-height:100%;}body{line-height:1.5;}img{max-width:100%;height:auto;}button,input,textarea,select{font:inherit;}a{color:inherit;}\n`;
  const componentRules = [];
  const responsiveCss = `/* Generated responsive rules */\n@media (max-width:1024px){body{overflow-x:hidden;}}\n@media (max-width:768px){[data-wf-id]{max-width:100%;}}\n@media (max-width:480px){h1{font-size:clamp(1.7rem,7vw,2.3rem);}}\n`;

  pages.forEach((page,index) => {
    const pageSlug = index === 0 ? 'index' : slugify(page.name);
    const roots = (page.children || []).map(id => graph.entities[id]).filter(Boolean);
    const allNodes = [];
    const walk = node => { allNodes.push(node); (node.children || []).map(id => graph.entities[id]).filter(Boolean).forEach(walk); };
    roots.forEach(walk);
    const pageRules = [];
    allNodes.forEach(node => {
      const rules = styleRules(node.data?.styles || {});
      if(rules) pageRules.push(`.wf-${node.id}{${rules}}`);
      if(node.data?.componentId && rules) componentRules.push(`.component-${slugify(node.data.componentId)}{${rules}}`);
    });
    files[`frontend/pages/${pageSlug}.html`] = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>${esc(page.name)}</title>\n<link rel="stylesheet" href="../css/global.css">\n<link rel="stylesheet" href="../css/components.css">\n<link rel="stylesheet" href="../css/pages/${pageSlug}.css">\n<link rel="stylesheet" href="../css/responsive.css">\n</head>\n<body>\n${roots.map(node => semanticNode(graph,node)).join('\n')}\n<script type="module" src="../js/app.js"></script>\n</body>\n</html>\n`;
    files[`frontend/css/pages/${pageSlug}.css`] = `/* ${page.name} page styles */\n${pageRules.join('\n')}\n`;
  });

  files['frontend/css/global.css'] = globalCss;
  files['frontend/css/components.css'] = `/* Shared component styles */\n${[...new Set(componentRules)].join('\n')}\n`;
  files['frontend/css/responsive.css'] = responsiveCss;
  files['frontend/js/app.js'] = `// Generated by WebForge\nexport function initWebForge(){\n  document.documentElement.dataset.webforgeReady='true';\n}\ninitWebForge();\n`;
  files['frontend/assets/placeholder.svg'] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450"><rect width="800" height="450" fill="#eef1f5"/><text x="400" y="225" text-anchor="middle" dominant-baseline="middle" font-family="sans-serif" font-size="28" fill="#7b8495">WebForge Image Placeholder</text></svg>`;
  files['README.md'] = `# WebForge Project\n\nGenerated semantic HTML with global, component, page, and responsive CSS layers.\n`;
  return files;
}

function canvasFallback(){
  const canvas = document.querySelector('#canvas');
  const roots = canvas ? [...canvas.children].filter(el => el.classList.contains('forge-node')) : [];
  const clone = node => { const copy=node.cloneNode(true); copy.querySelectorAll('.resize-handle').forEach(h=>h.remove()); copy.classList.remove('selected'); return copy; };
  return { 'frontend/pages/index.html': `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WebForge Export</title></head><body>${roots.map(node=>clone(node).outerHTML).join('\n')}</body></html>` };
}

const enc = new TextEncoder();
function crc32(bytes){let table=crc32.table;if(!table){table=crc32.table=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});}let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function u16(n){return new Uint8Array([n&255,(n>>>8)&255]);}
function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);}
function zip(files){const locals=[],central=[];let offset=0;for(const [path,text] of Object.entries(files)){const name=enc.encode(path),data=enc.encode(text),crc=crc32(data),local=new Uint8Array(30+name.length+data.length);local.set([80,75,3,4,20,0,0,0,0,0,0,0,0,0],0);local.set(u32(crc),14);local.set(u32(data.length),18);local.set(u32(data.length),22);local.set(u16(name.length),26);local.set(u16(0),28);local.set(name,30);local.set(data,30+name.length);locals.push(local);const dir=new Uint8Array(46+name.length);dir.set([80,75,1,2,20,0,20,0,0,0,0,0,0,0,0,0],0);dir.set(u32(crc),16);dir.set(u32(data.length),20);dir.set(u32(data.length),24);dir.set(u16(name.length),28);dir.set(u16(0),30);dir.set(u16(0),32);dir.set(u16(0),34);dir.set(u16(0),36);dir.set(u32(offset),42);dir.set(name,46);central.push(dir);offset+=local.length;}const centralSize=central.reduce((n,b)=>n+b.length,0),end=new Uint8Array(22);end.set([80,75,5,6,0,0,0,0],0);end.set(u16(central.length),8);end.set(u16(central.length),10);end.set(u32(centralSize),12);end.set(u32(offset),16);const out=new Uint8Array(offset+centralSize+22);let p=0;for(const b of locals){out.set(b,p);p+=b.length;}for(const b of central){out.set(b,p);p+=b.length;}out.set(end,p);return new Blob([out],{type:'application/zip'});}

export function generateProjectDownload(){
  const graph = window.webforge?.getGraph?.();
  const files = graph?.entities ? collectGraphFiles(graph) : canvasFallback();
  const blob=zip(files),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='webforge-generated-project.zip';a.click();URL.revokeObjectURL(a.href);
  window.dispatchEvent(new CustomEvent('webforge:generated',{detail:{version:16,files}}));
  return files;
}

export { collectGraphFiles };
