function safeName(name='index'){return String(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'index';}
function styleRules(el){const props=['width','minHeight','background','color','padding','margin','borderRadius','display','flexDirection','gap','gridTemplateColumns','position','left','top'];return props.map(p=>{const v=el.style[p];if(!v)return '';const cssName=p.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`);return `${cssName}:${v};`}).join('');}
function cloneForSource(node){const clone=node.cloneNode(true);clone.querySelectorAll('.resize-handle').forEach(h=>h.remove());return clone;}
export function collectVisualProject(){
  const canvas=document.querySelector('#canvas');
  const roots=[...canvas.children].filter(el=>el.classList.contains('forge-node'));
  let count=0;const css=[];
  const walk=el=>{const id=el.dataset.id||`node-${++count}`;el.classList.remove('selected');css.push(`.wf-${id}{${styleRules(el)}}`);cloneForSource(el).classList.add(`wf-${id}`);[...el.children].filter(c=>c.classList.contains('forge-node')).forEach(walk);};
  roots.forEach(walk);
  const source=roots.map(cloneForSource).map(el=>{el.className=Array.from(el.classList).filter(c=>c!=='selected').concat([...el.querySelectorAll('.forge-node')].flatMap(c=>[`wf-${c.dataset.id}`])).join(' ');return el.outerHTML;}).join('\n');
  return {html:`<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>WebForge Export</title>\n<link rel="stylesheet" href="../css/page.css">\n</head>\n<body>\n${source}\n<script type="module" src="../js/app.js"></script>\n</body>\n</html>\n`,css:`/* Generated by WebForge */\n${css.join('\n')}\n`,js:`// Generated by WebForge\n\ndocument.querySelectorAll('[data-id]').forEach(node => {\n  node.dataset.webforgeReady = 'true';\n});\n`};
}

export function generateProjectDownload(){
  const files=collectVisualProject();
  const payload={version:1,generatedAt:new Date().toISOString(),files:{'frontend/pages/index.html':files.html,'frontend/css/page.css':files.css,'frontend/js/app.js':files.js,'README.md':'# WebForge Project\n\nGenerated from the WebForge visual editor.\n'}};
  const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});
  const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='webforge-generated-project.json';a.click();URL.revokeObjectURL(a.href);
  window.dispatchEvent(new CustomEvent('webforge:generated',{detail:payload}));
  return payload;
}
