const MODES=['lock-layout','auto-adjust','make-individually'];
const DEVICES=['desktop','tablet','mobile'];
const STYLE_KEYS=['width','minHeight','position','left','top','padding','margin','flexDirection','gap','gridTemplateColumns','background','color','borderRadius','display'];
const clone=value=>structuredClone(value??{});
const device=()=>document.querySelector('[data-device].active')?.dataset.device||'desktop';
const selected=()=>document.querySelector('#canvas .forge-node.selected');
const graph=()=>window.webforge?.getGraph?.()||null;
const selectedEntity=()=>{const g=graph(),el=selected();return g&&el?.dataset.id?g.entities?.[el.dataset.id]||null:null};
const snapshot=el=>Object.fromEntries(STYLE_KEYS.map(key=>[key,el?.style?.[key]||'']));
const baseStyles=node=>({...node?.data?.styles||{}});
const state=node=>{const responsive=node?.data?.responsive||{};return{mode:responsive.mode||'auto-adjust',styles:{desktop:{...(responsive.styles?.desktop||{})},tablet:{...(responsive.styles?.tablet||{})},mobile:{...(responsive.styles?.mobile||{})}}}};
function saveGraph(next){window.webforge?.replaceGraph?.(next)}
function autoStyles(node,currentDevice){const s=baseStyles(node);if(currentDevice==='desktop')return s;const next={...s,maxWidth:'100%',boxSizing:'border-box',left:'0px',top:'0px'};if(next.width&&/^\d+(\.\d+)?px$/.test(next.width))next.width=`min(100%, ${next.width})`;if(currentDevice==='mobile'){if(next.display==='grid')next.gridTemplateColumns='1fr';if(next.display==='flex')next.flexDirection='column';if(next.padding)next.padding='min(18px, 4vw)';if(next.margin)next.margin='min(18px, 4vw)'}else if(next.display==='grid'&&next.gridTemplateColumns)next.gridTemplateColumns='repeat(2,minmax(0,1fr))';return next}
function stylesFor(node,currentDevice){const s=state(node);if(currentDevice==='desktop')return baseStyles(node);if(s.mode==='lock-layout')return baseStyles(node);if(s.mode==='make-individually')return{...baseStyles(node),...(s.styles[currentDevice]||{})};return autoStyles(node,currentDevice)}
function applyAll(){const g=graph();if(!g)return;const currentDevice=device();document.querySelectorAll('#canvas .forge-node[data-id]').forEach(el=>{const node=g.entities?.[el.dataset.id];if(!node)return;Object.entries(stylesFor(node,currentDevice)).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=='')el.style[key]=value});el.dataset.responsiveMode=state(node).mode});renderState()}
function setMode(mode){if(!MODES.includes(mode))return;const g=graph(),el=selected();if(!g||!el?.dataset.id)return;const id=el.dataset.id,node=g.entities[id],current=state(node),next=clone(g);const styles={...current.styles};const currentDevice=device();if(mode==='make-individually'&&!Object.keys(styles[currentDevice]||{}).length)styles[currentDevice]=snapshot(el);next.entities[id].data={...next.entities[id].data,responsive:{...current,mode,styles}};saveGraph(next);setTimeout(applyAll,0)}
function captureResponsiveEdit(event){const currentDevice=device();if(currentDevice==='desktop')return;const target=event.target;if(!['INPUT','SELECT','TEXTAREA'].includes(target.tagName))return;const el=selected(),g=graph();if(!el?.dataset.id||!g)return;const node=g.entities[el.dataset.id],current=state(node);if(current.mode!=='make-individually'){event.preventDefault();event.stopImmediatePropagation();renderState();return}const map={radius:'borderRadius',gridColumns:'gridTemplateColumns'};const key=map[target.id]||target.id;if(!STYLE_KEYS.includes(key))return;event.preventDefault();event.stopImmediatePropagation();const next=clone(g);const styles={...current.styles,[currentDevice]:{...current.styles[currentDevice],[key]:target.value}};next.entities[el.dataset.id].data={...next.entities[el.dataset.id].data,responsive:{...current,styles}};saveGraph(next);setTimeout(applyAll,0)}
function renderState(){const el=selected(),g=graph(),node=el&&g?.entities?.[el.dataset.id],mode=node?state(node).mode:null;document.querySelectorAll('[data-responsive-mode]').forEach(button=>button.classList.toggle('active',button.dataset.responsiveMode===mode));const status=document.querySelector('#responsiveStatus');if(status)status.textContent=mode?mode.replaceAll('-',' '):'Select an element'}
function mount(){const toolbar=document.querySelector('#responsiveControls');if(!toolbar)return;toolbar.addEventListener('click',event=>{const button=event.target.closest('[data-responsive-mode]');if(button)setMode(button.dataset.responsiveMode)});const inspector=document.querySelector('#inspector');if(inspector&&!inspector.dataset.responsiveGraphGuard){inspector.dataset.responsiveGraphGuard='1';inspector.addEventListener('change',captureResponsiveEdit,true)};document.querySelectorAll('[data-device]').forEach(button=>button.addEventListener('click',()=>setTimeout(applyAll,0)));window.addEventListener('webforge:graphchange',()=>setTimeout(applyAll,0));const observer=new MutationObserver(()=>setTimeout(renderState,0));const canvas=document.querySelector('#canvas');if(canvas)observer.observe(canvas,{childList:true,subtree:true});renderState();setTimeout(applyAll,150)}
async function mountV24(){const [{openPageMap},{getNavigationGraph}]=await Promise.all([import('./pageMap.js'),import('./navigationEditor.js')]);window.webforge ||= {};window.webforge.getNavigationGraph=getNavigationGraph;const actions=document.querySelector('.actions');if(actions&&!document.querySelector('#pageMapBtn')){const btn=document.createElement('button');btn.id='pageMapBtn';btn.textContent='Page Map';btn.title='Visual navigation map';btn.onclick=openPageMap;actions.insertBefore(btn,actions.firstChild)} }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();mountV24()});else{mount();mountV24()}
export{MODES,setMode,renderState,stylesFor,applyAll};
