const esc = (value='') => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const css = styles => Object.entries(styles || {}).filter(([,v])=>v!=='' && v!=null && v!=='auto').map(([k,v]) => `${k.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}:${v};`).join('');
const elementTag = type => ({heading:'h1',text:'p',button:'button',image:'div',section:'section'}[type] || 'div');

function renderNode(graph,node,depth=0){
  const type=node.data?.type || 'div';
  const tag=elementTag(type);
  const attrs=` class="wf-${node.id}" data-wf-id="${node.id}"`;
  const children=(node.children||[]).map(id=>graph.entities[id]).filter(Boolean).map(child=>renderNode(graph,child,depth+1)).join('');
  const content=type==='image'?'<span>Image placeholder</span>':(node.data?.content||'');
  if(type==='button') return `<button${attrs}>${esc((node.data?.content||'').replace(/<[^>]+>/g,''))}${children}</button>`;
  return `<${tag}${attrs}>${type!=='heading'&&type!=='text'&&type!=='section'?content:content}${children}</${tag}>`;
}

export function generatePage(graph,pageId,{title='WebForge Page',scriptPath='../js/app.js',stylePath='../css/page.css'}={}){
  const page=graph.entities[pageId];
  if(!page) throw new Error(`Page not found: ${pageId}`);
  const body=(page.children||[]).map(id=>graph.entities[id]).filter(Boolean).map(node=>renderNode(graph,node)).join('\n');
  return `<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width,initial-scale=1">\n  <title>${esc(title)}</title>\n  <link rel="stylesheet" href="${stylePath}">\n</head>\n<body>\n${body}\n<script type="module" src="${scriptPath}"></script>\n</body>\n</html>\n`;
}

export function generateCss(graph,pageId){
  const page=graph.entities[pageId];
  if(!page) throw new Error(`Page not found: ${pageId}`);
  const out=[];
  const walk=id=>{const n=graph.entities[id];if(!n)return;const styles=n.data?.styles||{};const rules=css(styles);if(rules)out.push(`.wf-${n.id}{${rules}}`);(n.children||[]).forEach(walk)};
  (page.children||[]).forEach(walk);
  return `/* Generated by WebForge */\n${out.join('\n')}\n`;
}

export function generateJs(){
  return `// Generated by WebForge\n\nexport function initWebForgeInteractions(){\n  document.querySelectorAll('[data-wf-id]').forEach(node=>{\n    node.dataset.webforgeReady='true';\n  });\n}\n\ninitWebForgeInteractions();\n`;
}

export function generateProjectFiles(graph){
  const pages=Object.values(graph.entities).filter(e=>e.type==='page');
  const files=[];
  pages.forEach((page,index)=>{
    const slug=index===0?'index':String(page.name||`page-${index+1}`).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') || `page-${index+1}`;
    files.push({path:`frontend/pages/${slug}.html`,language:'html',kind:'source',content:generatePage(graph,page.id,{title:page.name,stylePath:'../css/page.css',scriptPath:'../js/app.js'})});
  });
  files.push({path:'frontend/css/page.css',language:'css',kind:'source',content:pages.map(p=>generateCss(graph,p.id)).join('\n')});
  files.push({path:'frontend/js/app.js',language:'javascript',kind:'source',content:generateJs()});
  files.push({path:'README.md',language:'markdown',kind:'docs',content:'# WebForge Project\n\nGenerated from the WebForge project graph.\n'});
  return files;
}
